FROM agent-windows-base

WORKDIR /src

# install poetry
RUN /scripts/wine-do.sh pip install poetry==1.4.2

# copy repo files
COPY main.py readme.md pyproject.toml poetry.lock ./
COPY agent/ agent/

# install dependencies
RUN /scripts/wine-do.sh poetry install
