FROM tobix/wine:stable

ENV WINEDEBUG -all
ENV WINEPREFIX /opt/wineprefix

RUN mkdir -p /scripts
COPY docker/windows/assets/wine-do.sh docker/windows/assets/wine-init.sh /scripts/
COPY docker/windows/assets/SHA256SUMS.txt docker/windows/assets/keys.gpg /tmp/helper/
COPY docker/windows/assets/mkuserwineprefix /opt/

# Prepare windows environment
RUN xvfb-run sh /scripts/wine-init.sh

ARG PYTHON_VERSION=3.11.3
ARG UPX_VERSION=3.96

WORKDIR /tmp/helper

RUN umask 0
RUN curl -LOOO \
    https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-amd64.exe{,.asc} \
    https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-win64.zip
RUN gpgv --keyring ./keys.gpg python-${PYTHON_VERSION}-amd64.exe.asc python-${PYTHON_VERSION}-amd64.exe
RUN sha256sum -c SHA256SUMS.txt
RUN xvfb-run sh -c "\
      wine python-${PYTHON_VERSION}-amd64.exe /quiet TargetDir=C:\\Python310 \
        Include_doc=0 InstallAllUsers=1 PrependPath=1; \
      wineserver -w"
RUN unzip upx*.zip
RUN mv -v upx*/upx.exe ${WINEPREFIX}/drive_c/windows/
