ignored:
    - DL3008 # warning: Pin versions in apt get install
    - SC1091 # info: Not following: File not included in mock.
    - DL3059 # info: Multiple consecutive `RUN` instructions. Consider consolidation.
