FROM python:3.11-alpine

WORKDIR /src

RUN apk update && apk add --no-cache curl

# install poetry
RUN curl -sSL https://install.python-poetry.org | python - --version 1.4.2
ENV PATH="/root/.local/bin:$PATH"

# copy repo files
COPY readme.md pyproject.toml poetry.lock ./
COPY agent/* agent/

# install dependencies
RUN poetry config virtualenvs.create false
RUN poetry install
RUN pip install pyinstaller
