FROM tobix/wine:stable

ENV WINEDEBUG -all
ENV WINEPREFIX /opt/wineprefix

RUN mkdir -p /scripts
COPY scripts/* /scripts/
COPY requirements.txt SHA256SUMS.txt keys.gpg /tmp/helper/
COPY mkuserwineprefix /opt/

# Prepare windows environment
RUN xvfb-run sh /scripts/wine-init.sh

ARG PYTHON_VERSION=3.11.3
ARG UPX_VERSION=3.96

WORKDIR /tmp/helper

RUN umask 0
RUN curl -LOOO \
    https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-amd64.exe{,.asc} \
    https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-win64.zip
RUN gpgv --keyring ./keys.gpg python-${PYTHON_VERSION}-amd64.exe.asc python-${PYTHON_VERSION}-amd64.exe
RUN sha256sum -c SHA256SUMS.txt
RUN xvfb-run sh -c "\
      wine python-${PYTHON_VERSION}-amd64.exe /quiet TargetDir=C:\\Python310 \
        Include_doc=0 InstallAllUsers=1 PrependPath=1; \
      wineserver -w"
RUN unzip upx*.zip
RUN mv -v upx*/upx.exe ${WINEPREFIX}/drive_c/windows/

RUN /scripts/wine-do.sh pip install -r /tmp/helper/requirements.txt
RUN /scripts/wine-do.sh pip install --no-warn-script-location pyinstaller

WORKDIR /

RUN rm -Rf helper
