#!/usr/bin/env bash

set -euo pipefail

REPO=
OUT=
TAG=latest
VERSION=main
BUCKET=s3://sema-agent-images

print-usage() {
  if [ "$#" != 0 ]; then
    printf '%s\n\n' "$@" >&2
  fi
  printf '%s\n' 'Usage: agent <repository> <output-directory>' >&2
  printf '\n' >&2
  printf '%s\n' 'Runs a Sema scan on the provided <repository>, and outputs a .zip file in ' >&2
  printf '%s\n' '<output-directory>. This .zip file must be sent to Sema for further analysis.' >&2
  printf '\n' >&2
  printf '%s\n' 'Options:' >&2
  printf '%s\n' '  -h, --help        Print this message.' >&2
  printf '%s\n' '  -t, --tag <tag>   Use the specified Docker image tag. Defaults to "latest".' >&2
}

check-usage() {
  if [ "$#" -lt 2 ]; then
    print-usage "Expected at least 2 arguments but got $#."
    exit 1
  fi

  while :; do
    case $1 in
      -h|-\?|--help)
        print-usage
        exit
        ;;
      -t|--tag)
        if [ "$2" ]; then
          TAG=$2
          VERSION=$TAG
          shift
        else
          print-usage 'ERROR: "--tag" requires a non-empty option argument.'
          exit 1
        fi
        ;;
      --)
        shift
        break
        ;;
      -?*)
        printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
        ;;
      *)
        break
    esac

    shift
  done

  REPO=$1
  OUT=$2

  # check that arguments are valid directories
  for DIR in "$REPO" "$OUT"; do
    if [ ! -d "$DIR" ]; then
      print-usage "'$DIR' is not a directory."
      exit 1
    fi
  done
}

abspath() {
  cd "$1"
  pwd -P
}

main() {
  check-usage "$@"

  IMAGE_FILE="out/$VERSION/agent-amd64.tar"
  CURL_ARGS=(-o "$IMAGE_FILE")

  # Sema internal use -- when AWS credentials are available
  S3URI="$BUCKET/$VERSION/"

  mkdir -p "out/$VERSION/"
  if aws s3 ls "$S3URI" > /dev/null 2>&1; then
    printf 'Downloading Agent image from %s...\n' "$S3URI"
    aws s3 sync "$S3URI" "out/$VERSION/"
  elif [ -f "download-url.txt" ]; then
    if [ -f "$IMAGE_FILE" ]; then
      # Only download the image if it's newer than the existing one
      CURL_ARGS+=(-z "$IMAGE_FILE")
    fi

    URL=$(cat download-url.txt)
    printf 'Downloading Agent image from %s...\n' "$URL"
    curl "${CURL_ARGS[@]}" "$URL"
  else
    printf 'ERROR: No Agent image found.\n'
    exit 1
  fi

  printf 'Loading Agent image...\n'
  docker load --input "$IMAGE_FILE"

  docker run \
    --rm \
    --mount type=bind,source="$(abspath $REPO)",target=/repo,readonly \
    --mount type=bind,source="$(abspath $OUT)",target=/out \
    ghcr.io/semalab/agent:$TAG --repository /repo --output /out
}

main "$@"
