name: Build and push Docker image

on:
  push:
    branches:
      - main
      - "[Ss][Qq]-*"
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: agent

      - name: Checkout backend-core
        uses: actions/checkout@v4
        with:
          repository: Semalab/backend-core
          token: ${{ secrets.GH_PAT }}
          path: backend-core

      - name: Checkout backend-activitypersistence
        uses: actions/checkout@v4
        with:
          repository: Semalab/backend-activitypersistence
          token: ${{ secrets.GH_PAT }}
          path: backend-activitypersistence

      - name: Checkout backend-commitanalysis
        uses: actions/checkout@v4
        with:
          repository: Semalab/backend-commitanalysis
          token: ${{ secrets.GH_PAT }}
          path: backend-commitanalysis

      - name: Checkout backend-gitblame
        uses: actions/checkout@v4
        with:
          repository: Semalab/backend-gitblame
          token: ${{ secrets.GH_PAT }}
          path: backend-gitblame

      - name: Checkout corresponding branches
        run: |
          for repo in backend-core backend-activitypersistence backend-commitanalysis; do
            pushd $repo
            if git ls-remote --exit-code --heads origin ${{ github.ref_name }}; then
              git fetch origin ${{ github.ref_name }}
              git switch --discard-changes ${{ github.ref_name }}
            else
              echo "Staying on default branch as ${{ github.ref_name }} does not exist in $repo"
            fi
            popd
          done

      - name: Build JARs
        working-directory: agent
        run: make build-jars

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up cache
        working-directory: agent
        run: mkdir -p cache

      - name: Cache downloaded data
        id: cache-download
        uses: actions/cache@v4
        with:
          path: agent/cache
          key: cache-download

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        id: build
        uses: docker/build-push-action@v5
        with:
          context: agent
          file: agent/docker/Dockerfile
          load: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: agent
          file: agent/docker/Dockerfile
          push: true
          provenance: false # Disabled because GitHub UI shows unknown/unknown images with it
          platforms: linux/amd64 # Add linux/arm64 when scancode becomes compatible with it
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Copy downloaded data to cache
        env:
          AGENT_TAG: ${{ steps.build.outputs.imageid }}
        working-directory: agent
        run: make save-cache
