FROM python:3.11-alpine

WORKDIR /src

RUN apk update && apk add --no-cache binutils

# install poetry
RUN pip install poetry==1.4.2

# copy repo files
COPY main.py readme.md pyproject.toml poetry.lock ./
COPY agent/ agent/

# install dependencies
RUN poetry install
