FROM python:3.8-buster

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install curl unzip

# ---------- dependencies ----------
WORKDIR /dependencies

# dependency_check: https://github.com/jeremylong/DependencyCheck
ARG DEPENDENCY_CHECK_VERSION=8.2.1

RUN apt-get -y install openjdk-11-jre-headless

RUN curl -L \
    https://github.com/jeremylong/DependencyCheck/releases/download/v${DEPENDENCY_CHECK_VERSION}/dependency-check-${DEPENDENCY_CHECK_VERSION}-release.zip \
    --output dependency-check.zip
RUN unzip dependency-check.zip
ENV AGENT_DEPENDENCY_CHECK=/dependencies/dependency-check

# scancode: https://github.com/nexB/scancode-toolkit
ARG SCANCODE_VERSION=31.2.6

RUN apt-get -y install python3-dev libbz2-1.0 xz-utils zlib1g libxml2-dev libxslt1-dev libpopt0

RUN curl -L \
    https://github.com/nexB/scancode-toolkit/releases/download/v${SCANCODE_VERSION}/scancode-toolkit-v${SCANCODE_VERSION}_py3.8-linux.tar.gz \
    --output scancode.tar.gz

RUN tar -xzf scancode.tar.gz
RUN echo "$(which python)" > scancode-toolkit-v${SCANCODE_VERSION}/PYTHON_EXECUTABLE
RUN cd scancode-toolkit-v${SCANCODE_VERSION}/ && ./configure
ENV AGENT_SCANCODE=/dependencies/scancode-toolkit-v${SCANCODE_VERSION}
